os:
  - linux

dist: xenial
services:
  - xvfb
language: node_js
node_js:
  - "6"
  - "7"
  - "8"

before_install:
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

script:
  - npm install
  - npm audit
  - gulp
